---
title: "Example WVPlots"
author: "Win-Vector LLC"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


```{r, fig.width=8, fig.height=8}
set.seed(34903490)
x = rnorm(50)
y = 0.5*x^2 + 2*x + rnorm(length(x))
frm = data.frame(x=x,y=y,yC=y>=as.numeric(quantile(y,probs=0.8)))
frm$absY <- abs(frm$y)
frm$posY = frm$y > 0
frm$costX = 1
```

```{r, fig.width=8, fig.height=8}
WVPlots::ScatterHist(frm, "x", "y", title="Example Fit")
```

```{r, fig.width=8, fig.height=8}
WVPlots::ScatterHist(frm, "x", "y", smoothmethod="lm", title="Example Linear Fit", annot_size=2)
```

```{r, fig.width=8, fig.height=8}
WVPlots::ScatterHist(frm, "x", "y", smoothmethod="identity", title="Example Relation Plot", annot_size=2)
```

```{r, fig.width=8, fig.height=8}
WVPlots::BinaryYScatterPlot(frm, "x", "posY", title="Example 'Probability of Y' Plot")

WVPlots::BinaryYScatterPlot(frm, "x", "posY", use_glm=TRUE, title="Example 'Probability of Y' Plot (GLM smoothing)")
```


```{r, fig.width=8, fig.height=8}
WVPlots::GainCurvePlot(frm, "x", "absY", title="Example Continuous Gain Curve")
```

```{r, fig.width=8, fig.height=8}
WVPlots::GainCurvePlotC(frm, "x", "costX", "absY", title="Example Continuous Gain CurveC")
```

```{r, fig.width=8, fig.height=8}
WVPlots::GainCurvePlot(frm, "x", "yC", title="Example Discrete Gain Curve")
```

```{r, fig.width=8, fig.height=8}
WVPlots::ROCPlot(frm, "x", "yC", title="Example ROC plot")
```

```{r, fig.width=8, fig.height=8}
WVPlots::DoubleDensityPlot(frm, "x", "yC", title="Example double density plot")
```



```{r, fig.width=8, fig.height=8}
set.seed(34903490)

# discrete variable: letters of the alphabet
# frequencies of letters in english
# source: http://en.algoritmy.net/article/40379/Letter-frequency-English
letterFreqs = c(8.167, 1.492, 2.782, 4.253, 12.702, 2.228,
                2.015, 6.094, 6.966, 0.153, 0.772, 4.025, 2.406, 6.749, 7.507, 1.929,
                0.095, 5.987, 6.327, 9.056, 2.758, 0.978, 2.360, 0.150, 1.974, 0.074)
letterFreqs = letterFreqs/100
letterFrame = data.frame(letter = letters, freq=letterFreqs)

# now let's generate letters according to their letter frequencies
N = 1000
randomDraws = data.frame(draw=1:N, letter=sample(letterFrame$letter, size=N, replace=TRUE, prob=letterFrame$freq))

WVPlots::ClevelandDotPlot(randomDraws, "letter", title = "Example Cleveland-style dot plot")
WVPlots::ClevelandDotPlot(randomDraws, "letter", limit_n = 10,  title = "Top 10 most frequent letters")
WVPlots::ClevelandDotPlot(randomDraws, "letter", sort=0, title="Example Cleveland-style dot plot, unsorted")
WVPlots::ClevelandDotPlot(randomDraws, "letter", sort=1, stem=FALSE, title="Example with increasing sort order + coord_flip, no stem") + ggplot2::coord_flip()

```

```{r, fig.width=8, fig.height=8}
classes = c("a", "b", "c")
means = c(2, 4, 3)
names(means) = classes
label = sample(classes, size=1000, replace=TRUE)
meas = means[label] + rnorm(1000)
frm2 = data.frame(label=label,
                  meas = meas)

WVPlots::ScatterBoxPlot(frm2, "label", "meas", pt_alpha=0.2, title="Example Scatter/Box plot")
WVPlots::ScatterBoxPlotH(frm2, "meas", "label",  pt_alpha=0.2, title="Example Scatter/Box plot")
```

```{r, fig.width=8, fig.height=8}
frmx = data.frame(x = rbinom(1000, 20, 0.5))
WVPlots::DiscreteDistribution(frmx, "x","Discrete example")
```

```{r, fig.width=8, fig.height=8}
y = c(1,2,3,4,5,10,15,18,20,25)
x = seq_len(length(y))
df = data.frame(x=x,y=y)

WVPlots::ConditionalSmoothedScatterPlot(df, "x", "y", NULL, title="centered smooth, one group")
WVPlots::ConditionalSmoothedScatterPlot(df, "x", "y", NULL, title="left smooth, one group", align="left")
WVPlots::ConditionalSmoothedScatterPlot(df, "x", "y", NULL, title="right smooth, one group", align="right")

n = length(x)
df = rbind(data.frame(x=x, y=y+rnorm(n), gp="times 1"),
           data.frame(x=x, y=0.5*y + rnorm(n), gp="times 1/2"),
           data.frame(x=x, y=2*y + rnorm(n), gp="times 2"))

WVPlots::ConditionalSmoothedScatterPlot(df, "x", "y", "gp", title="centered smooth, multigroup")
WVPlots::ConditionalSmoothedScatterPlot(df, "x", "y", "gp", title="left smooth, multigroup", align="left")
WVPlots::ConditionalSmoothedScatterPlot(df, "x", "y", "gp", title="right smooth, multigroup", align="right")
```

```{r, fig.width=8, fig.height=8}
WVPlots::DoubleHistogramPlot(frm, "x", "yC", title="Example double histogram plot")
```

```{r, fig.width=8, fig.height=8}
WVPlots::ConditionalDistributionPlot(frm, "x", "yC", title="Example conditional distribution plot")
```


```{r, fig.width=8, fig.height=8}
set.seed(52523)
d <- data.frame(wt=100*rnorm(100))
WVPlots::PlotDistCountNormal(d,'wt','example')
WVPlots::PlotDistDensityNormal(d,'wt','example')
```
